spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/idp
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: dbuser

rate:
  starter:
    mode: current-day
    currencies[0]: EUR
    currencies[1]: USD
    enable-cross-rate: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
